### PR TITLE
docs: Project GitHub actions #285

### LINKED ISSUE #285: docs: project github actions
### Overview

We need to add documentation for the github actions being used in this repo for the benefit of developers and maintainers so that they can understand how to read the results in the Actions page.

### Action Items

- [x] Add a page if this is a new topic
- [x] Add documentation

### Instructions

`What to include in the documentation`

### PR DESCRIPTION
**Pull request by fyliu**
- Fixes #285

### What changes did you make?

- created a documentation page to summarize github actions used and run in the project
- removed the create card action we no longer use with the new project

### Why did you make the changes (we will use this info to test)?

- to make it clear to readers looking at the files or the Actions page on Github

### Screenshot

Visuals after changes are applied

image

### CODE REVIEW

**Comment by fyliu** [comment]
The new project migration this week will change the contents of this PR. I'm setting this to graft to wait for that.

**Comment by drakeredwind01** [comment]
the picture doesn't match the code

**Review by drakeredwind01 — DISMISSED** [review]
the code doesn't match the image

**Comment by fyliu** [comment]
@drakeredwind01 I updated the screenshot and file. Can you please take a look? Thanks!

**Review by ExperimentsInHonesty — APPROVED** [review]

**Pull request merged**
