### PR TITLE
Create table language 54

### LINKED ISSUE #54: Create Table: language :smile:
### Overview

We need to create the language table so that we can update a shared data store across hackforla.org, vrms, civictechjobs, and tables (onboarding) project.

#### Details

A table and a model are the same thing

### Action Items

- [x] identify and document table description (see spreadsheet under Resources)
  - [x] if not, reach out to PD leads
- [x] compare and check off the data fields (below) against the ERD. Note any fields in the ERD that's missing from the list. (see Resources)
- [x] create a single model in Django (defining schema)
- [x] compare the check off associated tables (below) against the ERD. Note any associated tables in the ERD that's missing from the list (see Resources)
- [ ] write a test for the relationships this model will have with other models (e.g., creating a user and assigning them a set of permissions on a project).
- [x] write an API end point
- [x] write API unit tests
- [x] document the endpoint
- [x] Release #64 from ice box

### Resources/Instructions

- See [People Depot Resources wiki page](https://github.com/hackforla/peopledepot/wiki/Resources-and-Links) for links
  - ERD
  - Table and Field Definitions
  - API Endpoint
- See the [wiki page](https://github.com/hackforla/peopledepot/wiki/Create-Table-issues-data-gathering-workflow) for instructions.

### Description

Dictionary of languages

### Data Fields

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)

    - [x] (PK) id - int - Record Id
    - [x] name - varchar
    - [x] description - textfield
    - [x] logo - url varchar
    - [x] updated - varchar

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - [ ] logo - URLField

### Associated Tables

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)
      - [x] project_language_xref (one-to-many)

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - None

### PR DESCRIPTION
**Pull request by AzaniaBG**
Fixes #54 
The how-to Guide indicates the read-only field is `updated_at` so I added that field instead of using the ERD's `updated_on` field.

### CODE REVIEW

**Review by fyliu — CHANGES_REQUESTED** [review]
Thanks for contributing the PR. I think the code looks great!

There's just a couple of chores that's missing.

1. It looks like you don't have pre-commit working. It should have fixed some of the whitespace and import ordering issues automatically. I'm able to tell because it would've sorted the import lines alphabetically in files like `models.py`.
1. You should always rebase your changes to the latest hackforla/main branch once you have it working and before submitting the PR. That way, if some other changes got merged, you’ll notice any conflicts and be able to fix them. The general thinking is whatever got merged into the upstream repo is working, and you’re trying to merge your working changes into it, but you have to make sure your changes can work with the latest code that’s there.
In general software development, sometimes the changes are in different files or different parts of the file so that they don’t conflict. But for us doing these “create table…” issues, the changes are all very similar and it’s pretty much going to conflict all the time.

A few notes half for myself:

- I should say that I'm noticing that the lint script doesn't seem to be doing what it should. I will need to debug that.
- I will also try to do the rebase for this PR and add the steps to some documentation page for future reference.
- There's also the issue of non-ideal situation where the pre-commit needs installation whereas the rest of the project just runs from docker. We'll have create an issue to put it into docker.

**Comment by fyliu** [comment]
I created issues to create the necessary docker config and docs so that you can help yourself. I can also show you how I would do this during the meeting.

**Comment by AzaniaBG** [comment]
Update: I'm still having issues fetching from upstream, so I can't run  rebase the changes. I thought I fixed the issue where my local repo was pulling from the fyliu repo., but apparently not. I believe Fang and I are going to work on this at today's meeting.

**Comment by AzaniaBG** [comment]
@fyliu ~ we rebased/resolved conflicts from `main` at last Thursday's meeting. I installed `pre-commit` and it appears to be working. I pushed my changes and requested a re-review. Let me know if you have any questions.

Update: this issue should be complete after Fang reviews/approves the PR. 
Availability for next week (week of 8/27):
Thursday and Friday: 6 - 7 AM
Saturday: 7 - 11 AM

**Review by fyliu — CHANGES_REQUESTED** [review]
Thanks for putting in the work to rebase the changes, but it looks like you might have done the rebase in the other direction, from the main branch onto the feature branch. Can you rebase from the feature branch to the main branch?

Here's the current state of your git history.
Screen Shot 2023-08-30 at 12 46 32 AM

This is the way to think about it: the code in `main` has already gone through review and merged. You have new changes that needs to be reviewed, and they should continue from where the current `main` branch ends. That's where I drew the red arrow to show how your first commit should be connected to `main`.

The way you have it now is your changes start before `main` and you took the last commit from `main` and applied it after your changes, essentially splitting `main` history. I know that the final code might end up being the same, but in reordering the commits, you're making the already-reviewed commits into commits that need review, because it's possible the way you applied Brenda's commit could have changed the functionality that's there.

The thing to remember is you can rewrite your own changes but not other people's changes. It's something repo maintainers won't allow to happen. Whatever commits are already in `main` shouldn't be changed, and new changes should be applied after.

You should instead create a new branch at "removed updated_on from field..." and run `git rebase main` and go through any conflict resolution steps for each of your commits. It's a good amount to do but that's what you would have to do to keep all of your commits. That's why I suggested before to squash them into one, or merge some of the fixer commits into the feature ones. I think it might be good if I could show you how I would do the rebase to keep all the commits. I've done really long rebases before and I'm fairly comfortable with the process.

**Comment by AzaniaBG** [comment]
> Thanks for putting in the work to rebase the changes, but it looks like you might have done the rebase in the other direction, from the main branch onto the feature branch. Can you rebase from the feature branch to the main branch?
> 
> Here's the current state of your git history. Screen Shot 2023-08-30 at 12 46 32 AM
> 
> This is the way to think about it: the code in `main` has already gone through review and merged. You have new changes that needs to be reviewed, and they should continue from where the current `main` branch ends. That's where I drew the red arrow to show how your first commit should be connected to `main`.
> 
> The way you have it now is your changes start before `main` and you took the last commit from `main` and applied it after your changes, essentially splitting `main` history. I know that the final code might end up being the same, but in reordering the commits, you're making the already-reviewed commits into commits that need review, because it's possible the way you applied Brenda's commit could have changed the functionality that's there.
> 
> The thing to remember is you can rewrite your own changes but not other people's changes. It's something repo maintainers won't allow to happen. Whatever commits are already in `main` shouldn't be changed, and new changes should be applied after.
> 
> You should instead create a new branch at "removed updated_on from field..." and run `git rebase main` and go through any conflict resolution steps for each of your commits. It's a good amount to do but that's what you would have to do to keep all of your commits. That's why I suggested before to squash them into one, or merge some of the fixer commits into the feature ones. I think it might be good if I could show you how I would do the rebase to keep all the commits. I've done really long rebases before and I'm fairly comfortable with the process.

@fyliu ~ after we rebased the feature branch last Thursday, I tried to push the changes and got an error about diverged branches and “failed to push some refs…”. That's why I had to resolve conflicts again. Can I merge the changes instead of rebasing them?

**Comment by fyliu** [comment]
@AzaniaBG Sure. Merge and resolve conflict works. It just has to be done so that the PR shows no conflicts. We can't resolve conflicts on github itself because the migration files need to be regenerated, and also I think it's a generally accepted practice for code contributors to do this part so that the maintainers don't have to. The reason is that the contributor has a better idea how and where the new code should be added to the code base.

Sorry to get into the weeds with git for this. I can do all this if you want. There's nothing wrong with your code other than some code formatting and the migration files. The rest is just a git exercise with the rebasing. It's good to know but this PR got complicated because of not having pre-commit to format the code at each commit.

I think this PR would make a good exercise for developers wanting to play with git rebase and to try different strategies because of the complications.

**Comment by fyliu** [comment]
I'm going to close this one since we're going to merge #195 instead.

**Pull request closed without merging**
